# Generated by Django 5.1.4 on 2024-12-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookGallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
